# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 03:16
from __future__ import unicode_literals

import activity.task.task_type
from django.db import migrations, models
import django.db.models.deletion
import ext.django.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAPAAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_no_relation_to_assessor', models.BooleanField()),
                ('bill_sighted', models.BooleanField()),
                ('is_name_on_bill', models.BooleanField()),
                ('is_address_on_bill', models.BooleanField()),
                ('is_residential_electicity_or_gas_account', models.BooleanField()),
                ('is_experiencing_financial_hardship', models.BooleanField()),
                ('is_denying_basic_needs', models.BooleanField()),
                ('is_facing_disconnection', models.BooleanField()),
                ('has_contacted_retailer_to_check_payment_plans', models.BooleanField()),
                ('has_contacted_retailer_to_check_energy_rebates', models.BooleanField()),
                ('has_contacted_retailer_to_check_updated_balance', models.BooleanField()),
                ('has_contacted_retailer_to_check_eapa_payments', models.BooleanField()),
                ('is_receiving_over_limit_on_current_bill', models.BooleanField()),
                ('is_receiving_over_limit_for_financial_year', models.BooleanField()),
                ('is_receiving_assistance_more_than_twice', models.BooleanField()),
                ('limit_exemption_description', models.TextField()),
                ('signed_privacy_agreement', models.BooleanField()),
                ('is_bill_stamped', models.BooleanField()),
                ('understood_voucher_processing', models.BooleanField()),
                ('consent_to_retain_data', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=ext.django.fields.EnumField(choices=[('issue_voucher', 'ISSUE_VOUCHER'), ('service_referral', 'EXTERNAL_SERVICE_REFERRAL')], default='ISSUE_VOUCHER', enum_type=activity.task.task_type.TaskType, max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChemistVoucher',
            fields=[
                ('voucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.Voucher')),
            ],
            bases=('activity.voucher',),
        ),
        migrations.CreateModel(
            name='EAPAVoucher',
            fields=[
                ('voucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.Voucher')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.EAPAAssessment')),
            ],
            bases=('activity.voucher',),
        ),
        migrations.CreateModel(
            name='FoodcareVoucher',
            fields=[
                ('voucher_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='activity.Voucher')),
                ('value', models.IntegerField()),
                ('expires', models.DateField()),
                ('redeemed', models.BooleanField(default=False)),
            ],
            bases=('activity.voucher',),
        ),
        migrations.AddField(
            model_name='voucher',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Task'),
        ),
    ]
