# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 09:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20160802_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='activity',
        ),
        migrations.AddField(
            model_name='task',
            name='at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 2, 9, 30, 45, 480921)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucher',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activity.Task'),
        ),
    ]
