# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20160802_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='member',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
