# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_auto_20160731_0827'),
        ('activity', '0004_auto_20160809_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eapavoucher',
            name='assessment',
        ),
        migrations.AddField(
            model_name='task',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EAPAAssessment',
        ),
    ]
