# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0024_auto_20160812_0140'),
        ('activity', '0005_auto_20160812_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='eapavoucher',
            name='all_vouchers_filled_in',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='consent_to_retain_data',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='electricity_bill',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='member.EnergyAccountBill'),
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='gas_bill',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='member.EnergyAccountBill'),
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='has_contacted_retailer_to_check_eapa_payments',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='has_contacted_retailer_to_check_energy_rebates',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='has_contacted_retailer_to_check_payment_plans',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='has_contacted_retailer_to_check_updated_balance',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='is_all_bills_stamped',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='is_denying_basic_needs',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='is_disconnected',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='is_facing_disconnection',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='is_granted_limit_exemption',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='is_no_relation_to_assessor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='limit_exemption_description',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='signed_privacy_agreement',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='understood_voucher_processing',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
