# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_remove_voucher_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='kind',
            field=models.CharField(default='activity.EAPAVoucher', max_length=32),
            preserve_default=False,
        ),
    ]
