# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_voucher_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eapavoucher',
            old_name='all_vouchers_filled_in',
            new_name='is_assessor_declaration_signed',
        ),
        migrations.RenameField(
            model_name='eapavoucher',
            old_name='consent_to_retain_data',
            new_name='is_customer_declaration_signed',
        ),
        migrations.RemoveField(
            model_name='eapavoucher',
            name='has_contacted_retailer_to_check_eapa_payments',
        ),
        migrations.RemoveField(
            model_name='eapavoucher',
            name='has_contacted_retailer_to_check_energy_rebates',
        ),
        migrations.RemoveField(
            model_name='eapavoucher',
            name='has_contacted_retailer_to_check_payment_plans',
        ),
        migrations.RemoveField(
            model_name='eapavoucher',
            name='has_contacted_retailer_to_check_updated_balance',
        ),
        migrations.RemoveField(
            model_name='eapavoucher',
            name='is_all_bills_stamped',
        ),
        migrations.RemoveField(
            model_name='eapavoucher',
            name='is_no_relation_to_assessor',
        ),
        migrations.RemoveField(
            model_name='eapavoucher',
            name='signed_privacy_agreement',
        ),
        migrations.RemoveField(
            model_name='eapavoucher',
            name='understood_voucher_processing',
        ),
    ]
