# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-08 15:41
from __future__ import unicode_literals

import activity.voucher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_auto_20160829_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='vouchers_in_financial_year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodcarevoucher',
            name='expires',
            field=models.DateField(default=activity.voucher.models.foodcare_voucher_expires),
        ),
    ]
