# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-20 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemist', '__first__'),
        ('activity', '0012_auto_20170608_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistvoucher',
            name='is_assessor_declaration_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chemistvoucher',
            name='is_granted_limit_exemption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chemistvoucher',
            name='limit_exemption_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chemistvoucher',
            name='prescription',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='chemist.ChemistPrescription'),
            preserve_default=False,
        ),
    ]
