# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ext.django.fields
import staff.staff_type


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='induction_survey',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.StaffInductionSurvey'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='type',
            field=ext.django.fields.EnumField(choices=[('PermanentStaff', 'PERMANENT_STAFF'), ('OfficeVolunteer', 'OFFICE_VOLUNTEER'), ('FoodcareVolunteer', 'FOODCARE_VOLUNTEER'), ('OtherVolunteer', 'OTHER_VOLUNTEER')], enum_type=staff.staff_type.StaffType, max_length=32),
        ),
    ]
