# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20160627_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffinductionsurvey',
            old_name='personaility_traits',
            new_name='traits',
        ),
    ]
