# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ext.django.fields
import member.basic.gender
import member.basic.income.benefit_type
import member.basic.income.income_type
import member.basic.income.proof_of_low_income
import member.basic.residential_status.residence_type
import member.basic.residential_status.residential_stability
import member.dependent.carer_rel.living_arrangement
import member.dependent.carer_rel.relation_type


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=32)),
                ('postcode', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Carer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CarerRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_arrangement', ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('never', 'NEVER'), ('occasional', 'OCCASIONAL'), ('part_time', 'PART_TIME'), ('full_time', 'FULL_TIME')], enum_type=member.dependent.carer_rel.living_arrangement.LivingArrangement, max_length=32)),
                ('relation_type', ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('no_familial_relation', 'NO_FAMILIAL_RELATION'), ('parent', 'PARENT'), ('partner_of_parent', 'PARTNER_OF_PARENT'), ('sibling', 'SIBLING'), ('other', 'OTHER_RELATION')], enum_type=member.dependent.carer_rel.relation_type.RelationType, max_length=32)),
                ('carer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Carer')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=10)),
                ('mobile', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('carers', models.ManyToManyField(through='member.CarerRel', to='member.Carer')),
            ],
        ),
        migrations.CreateModel(
            name='EAPAAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_no_relation_to_assessor', models.BooleanField()),
                ('bill_sighted', models.BooleanField()),
                ('is_name_on_bill', models.BooleanField()),
                ('is_address_on_bill', models.BooleanField()),
                ('is_residential_electicity_or_gas_account', models.BooleanField()),
                ('is_experiencing_financial_hardship', models.BooleanField()),
                ('is_denying_basic_needs', models.BooleanField()),
                ('is_facing_disconnection', models.BooleanField()),
                ('has_contacted_retailer_to_check_payment_plans', models.BooleanField()),
                ('has_contacted_retailer_to_check_energy_rebates', models.BooleanField()),
                ('has_contacted_retailer_to_check_updated_balance', models.BooleanField()),
                ('has_contacted_retailer_to_check_eapa_payments', models.BooleanField()),
                ('is_receiving_over_limit_on_current_bill', models.BooleanField()),
                ('is_receiving_over_limit_for_financial_year', models.BooleanField()),
                ('is_receiving_assistance_more_than_twice', models.BooleanField()),
                ('limit_exemption_description', models.TextField()),
                ('signed_privacy_agreement', models.BooleanField()),
                ('is_bill_stamped', models.BooleanField()),
                ('understood_voucher_processing', models.BooleanField()),
                ('consent_to_retain_data', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EAPAVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.EAPAAssessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoodcareVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('expires', models.DateField()),
                ('redeemed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', ext.django.fields.EnumField(choices=[('none', 'NONE'), ('not_disclosed', 'NOT_DISCLOSED'), ('centrelink_benefit', 'CENTRELINK_BENEFIT'), ('partially_employed', 'PARTIALLY_EMPLOYED'), ('fully_employed', 'FULLY_EMPLOYED'), ('self_employed', 'SELF_EMPLOYED'), ('self_funded_retiree', 'SELF_FUNDED_RETIREE')], enum_type=member.basic.income.income_type.IncomeType, max_length=32)),
                ('proof_of_low_income', ext.django.fields.EnumField(choices=[('no_proof', 'NO_PROOF'), ('pensioner_concession_card_sighted', 'PENSIONER_CONCESSION_CARD'), ('low_income_health_care_card_sighted', 'LOW_INCOME_HEALTH_CARE_CARD')], enum_type=member.basic.income.proof_of_low_income.ProofOfLowIncome, max_length=32)),
                ('benefit_type', ext.django.fields.EnumField(choices=[('none', 'NONE'), ('not_disclosed', 'NOT_DISCLOSED'), ('newstart', 'NEWSTART'), ('aged', 'AGED'), ('disability', 'DISABILITY'), ('carer', 'CARER'), ('youth_allowance', 'YOUTH_ALLOWANCE'), ('abstudy', 'ABSTUDY'), ('austudy', 'AUSTUDY'), ('family_tax_benefit', 'FAMILY_TAX_BENEFIT'), ('parenting_payment_partnered', 'PARENTING_PAYMENT_PARTNERED'), ('parenting_payment_single', 'PARENTING_PAYMENT_SINGLE'), ('other', 'OTHER')], enum_type=member.basic.income.benefit_type.BenefitType, max_length=32)),
                ('benefit_other_description', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('male', 'MALE'), ('female', 'FEMALE')], enum_type=member.basic.gender.Gender, max_length=32)),
                ('date_of_birth', models.DateField()),
                ('aboriginal_or_torres_strait_islander', models.NullBooleanField()),
                ('register_consent', models.NullBooleanField()),
                ('is_partnered', models.NullBooleanField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Address')),
                ('carer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_carer', to='member.Carer')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Contact')),
                ('income', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Income')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('alias', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentialStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('none', 'NONE'), ('caravan_park', 'CARAVAN_PARK'), ('motel', 'MOTEL'), ('private_rental_landlord', 'PRIVATE_RENTAL_LANDLORD'), ('private_rental_real_estate', 'PRIVATE_RENTAL_REAL_ESTATE'), ('public_housing', 'PUBLIC_HOUSING'), ('community_housing', 'COMMUNITY_HOUSING'), ('own_home', 'OWN_HOME')], enum_type=member.basic.residential_status.residence_type.ResidenceType, max_length=32)),
                ('stability', ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('no_fixed_address', 'NO_FIXED_ADDRESS'), ('temporary', 'TEMPORARY'), ('permanent', 'PERMANENT')], enum_type=member.basic.residential_status.residential_stability.ResidentialStability, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MemberPartner',
            fields=[
                ('partner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.Partner')),
            ],
            bases=('member.partner',),
        ),
        migrations.CreateModel(
            name='NonMemberPartner',
            fields=[
                ('partner_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.Partner')),
                ('gender', ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('male', 'MALE'), ('female', 'FEMALE')], enum_type=member.basic.gender.Gender, max_length=32)),
                ('carer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Carer')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Contact')),
                ('income', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Income')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Name')),
            ],
            bases=('member.partner',),
        ),
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Name'),
        ),
        migrations.AddField(
            model_name='member',
            name='partner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Partner'),
        ),
        migrations.AddField(
            model_name='member',
            name='residential_status',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.ResidentialStatus'),
        ),
        migrations.AddField(
            model_name='dependent',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Name'),
        ),
        migrations.AddField(
            model_name='carerrel',
            name='dependent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Dependent'),
        ),
        migrations.AddField(
            model_name='memberpartner',
            name='_member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
