# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 01:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eapavoucher',
            name='date_issued',
            field=models.DateField(default=datetime.date(2016, 7, 17)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodcarevoucher',
            name='date_issued',
            field=models.DateField(default=datetime.date(2016, 7, 17)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodcarevoucher',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
            preserve_default=False,
        ),
    ]
