# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 01:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20160617_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
        ),
        migrations.RemoveField(
            model_name='eapavoucher',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='eapavoucher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='eapavoucher',
            name='member',
        ),
        migrations.RemoveField(
            model_name='foodcarevoucher',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='foodcarevoucher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='foodcarevoucher',
            name='member',
        ),
        migrations.AddField(
            model_name='eapavoucher',
            name='voucher_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.Voucher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodcarevoucher',
            name='voucher_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.Voucher'),
            preserve_default=False,
        ),
    ]
