# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20160617_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='kind',
            field=models.CharField(default='member.voucher::EAPAVoucher', max_length=32),
            preserve_default=False,
        ),
    ]
