# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import ext.django.fields
import member.basic.energy_account.energy_retailer


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_voucher_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retailer', ext.django.fields.EnumField(choices=[('NotDisclosed', 'NOT_DISCLOSED'), ('Agl', 'AGL'), ('ClickEnergy', 'CLICK_ENERGY'), ('Dodo', 'DODO'), ('EnergyAustralia', 'ENERGY_AUSTRALIA'), ('Origin', 'ORIGIN'), ('RedEnergy', 'RED_ENERGY')], enum_type=member.basic.energy_account.energy_retailer.EnergyRetailer, max_length=32)),
                ('account_number', models.CharField(max_length=32)),
            ],
        ),
    ]
