# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import ext.django.fields
import member.basic.energy_account.energy_retailer


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20160627_0120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Benefit',
        ),
        migrations.AlterField(
            model_name='energyaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='energyaccount',
            name='retailer',
            field=ext.django.fields.EnumField(choices=[('NotDisclosed', 'NOT_DISCLOSED'), ('Agl', 'AGL'), ('ClickEnergy', 'CLICK_ENERGY'), ('Dodo', 'DODO'), ('EnergyAustralia', 'ENERGY_AUSTRALIA'), ('Origin', 'ORIGIN'), ('RedEnergy', 'RED_ENERGY')], enum_type=member.basic.energy_account.energy_retailer.EnergyRetailer, max_length=32, null=True),
        ),
    ]
