# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20160707_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipterm',
            name='renewed',
            field=models.DateTimeField(null=True),
        ),
    ]
