# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 07:43
from __future__ import unicode_literals

from datetime import datetime

from django.db import migrations
from member.models import Member
from member.membership_term.models import MembershipTerm, MembershipTermType

def upgrade_members(apps, schema_editor):
    members = Member.objects.all()
    for member in members:
        add_membership_term_to_member(member)

def add_membership_term_to_member(member):
    membership_term = MembershipTerm.objects.create(
        type=MembershipTermType.temporary,
        joined=datetime.now(),
        renewed=None,
        expires=datetime.now()
    )
    member.term = membership_term
    member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20160707_0755'),
    ]

    operations = [
        migrations.RunPython(upgrade_members)
    ]
