# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_add_membership_term_to_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.MembershipTerm'),
        ),
    ]
