# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20160627_0120'),
        ('member', '0013_auto_20160707_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFileNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.StaffMember')),
            ],
        ),
    ]
