# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_memberfilenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberfilenote',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
