# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 09:16
from __future__ import unicode_literals

from django.db import migrations
import ext.django.fields
import member.file_notes.severity


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_auto_20160708_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberfilenote',
            name='severity',
            field=ext.django.fields.EnumField(choices=[('info', 'INFO'), ('warning', 'WARNING'), ('error', 'ERROR')], default='INFO', enum_type=member.file_notes.severity.Severity, max_length=32),
            preserve_default=False,
        ),
    ]
