# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import ext.django.fields
import member.basic.gender
import member.file_notes.severity


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_memberfilenote_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], enum_type=member.basic.gender.Gender, max_length=32),
        ),
        migrations.AlterField(
            model_name='memberfilenote',
            name='severity',
            field=ext.django.fields.EnumField(choices=[('info', 'INFO'), ('warning', 'WARNING'), ('danger', 'DANGER')], enum_type=member.file_notes.severity.Severity, max_length=32),
        ),
        migrations.AlterField(
            model_name='nonmemberpartner',
            name='gender',
            field=ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], enum_type=member.basic.gender.Gender, max_length=32),
        ),
    ]
