# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ext.django.fields
import member.basic.gender
import member.membership_term.term_type


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_auto_20160723_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependent',
            name='gender',
            field=ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='NOT_DISCLOSED', enum_type=member.basic.gender.Gender, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='partner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='membershipterm',
            name='type',
            field=ext.django.fields.EnumField(choices=[('temporary', 'TEMPORARY'), ('associate', 'ASSOCIATE'), ('general', 'GENERAL'), ('partner', 'PARTNER')], enum_type=member.membership_term.term_type.MembershipTermType, max_length=32),
        ),
    ]
