# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_auto_20160725_0240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carer',
            name='role',
        ),
    ]
