# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 03:40
from __future__ import unicode_literals

from django.db import migrations
import ext.django.fields
import member.basic.gender
import member.dependent.carer_rel.relation_type


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_auto_20160729_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carerrel',
            name='relation_type',
            field=ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('no_familial_relation', 'NO_RELATION'), ('parent', 'PARENT'), ('partner_of_parent', 'PARTNER_OF_PARENT'), ('sibling', 'SIBLING'), ('other', 'OTHER_RELATION')], enum_type=member.dependent.carer_rel.relation_type.RelationType, max_length=32),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='gender',
            field=ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='NOT_DISCLOSED', enum_type=member.basic.gender.Gender, max_length=32),
            preserve_default=False,
        ),
    ]
