# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ext.django.fields
import member.basic.energy_account.account_type
import member.basic.energy_account.energy_retailer


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_auto_20160729_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='energy_account',
        ),
        migrations.AddField(
            model_name='energyaccount',
            name='type',
            field=ext.django.fields.EnumField(choices=[('gas', 'GAS'), ('electricity', 'ELECTRICITY')], default='ELECTRICITY', enum_type=member.basic.energy_account.account_type.EnergyAccountType, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='electricity_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='member.EnergyAccount'),
        ),
        migrations.AddField(
            model_name='member',
            name='gas_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='member.EnergyAccount'),
        ),
        migrations.AlterField(
            model_name='energyaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='energyaccount',
            name='retailer',
            field=ext.django.fields.EnumField(choices=[('NotDisclosed', 'NOT_DISCLOSED'), ('Agl', 'AGL'), ('ClickEnergy', 'CLICK_ENERGY'), ('Dodo', 'DODO'), ('EnergyAustralia', 'ENERGY_AUSTRALIA'), ('Origin', 'ORIGIN'), ('RedEnergy', 'RED_ENERGY')], default='NOT_DISCLOSED', enum_type=member.basic.energy_account.energy_retailer.EnergyRetailer, max_length=32),
            preserve_default=False,
        ),
    ]
