# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0024_auto_20160812_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyaccountbill',
            name='is_address_on_bill',
        ),
        migrations.RemoveField(
            model_name='energyaccountbill',
            name='is_name_on_bill',
        ),
    ]
