# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0026_remove_energyaccount_is_residential'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 5, 3, 10, 48, 50930)),
            preserve_default=False,
        ),
    ]
