# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 16:27
from __future__ import unicode_literals

from django.db import migrations
import ext.django.fields
import member.basic.residential_status.residence_type


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0027_member_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentialstatus',
            name='type',
            field=ext.django.fields.EnumField(choices=[('not_disclosed', 'NOT_DISCLOSED'), ('none', 'NONE'), ('caravan_park', 'CARAVAN_PARK'), ('motel', 'MOTEL'), ('boarding', 'BOARDING'), ('private_rental_landlord', 'PRIVATE_RENTAL_LANDLORD'), ('private_rental_real_estate', 'PRIVATE_RENTAL_REAL_ESTATE'), ('public_housing', 'PUBLIC_HOUSING'), ('community_housing', 'COMMUNITY_HOUSING'), ('own_home', 'OWN_HOME')], default='NOT_DISCLOSED', enum_type=member.basic.residential_status.residence_type.ResidenceType, max_length=32),
        ),
    ]
